################################################################################
# General configuration                                                        #
################################################################################

general:
  pdx: False


################################################################################
# Input configuration                                                          #
################################################################################

input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: 'input'

  # Optional: configuration to use for remote (FTP) input files.
  # ftp:
  #   username: 'user'
  #   password: 'pass'


################################################################################
# Rule configuration                                                           #
################################################################################

#### General/shared rules ####

cutadapt:
  # Example trims Illumina Truseq PE adapters, removes low quality bases and
  # drops any mates with either read shorter than 60bp after trimming.
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    -q 20
    --minimum-length 60

fastqc:
  extra: ''

bwa:
  index: '/path/to/index'
  # Host genome index, only required for PDX samples. If used,
  # index (above) should refer to the graft genome index.
  index_host: '/path/to/host_index'
  # Extra argument for adding read group information (which is critical
  # for many downstream steps). Replace 'CENTRE' with the name of your
  # company/institute.
  extra: "-M -R \"@RG\\tID:{sample}.{lane}\\tSM:{sample}\\tLB:{sample}\\t\
          PU:{sample}.{lane}\\tPL:ILLUMINA\\tCN:CENTRE\""
  sort_extra: ''
  threads: 5

samtools_merge:
  extra: ''
  threads: 5

picard_mark_duplicates:
  extra: >-
    -XX:ParallelGCThreads=5
    VALIDATION_STRINGENCY=LENIENT

picard_collect_hs_metrics:
    reference: 'input/genome.fa'
    bait_intervals: 'input/capture.intervals'
    target_intervals: 'input/capture.intervals'
    extra: '-Xmx4g'

multiqc:
  extra: ''


#### PDX-specific rules ####

disambiguate:
  extra: ''

sambamba_sort:
  extra: ''
  threads: 5
